# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de02d4a629b6c1621f9855724256c5abf7ec4f3b0e41731c39209705bb1957029e511406f0de832935e4bb20e016833d029f084febc3fe3a1a8091d6bbcbea9

test:
  secret_key_base: d14bccc39e2922df62f5689635a9c9e8a1b2a84f1596de0f0e4e5af3642bcb82c5639e4a6cb7efdb54e1431b039ef0be1b57afa0312f545eab3cf3cac8d30389

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
